---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: chart-repo
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/ethanliuu/chart-repo

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: chart-repo
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./muilt-apps
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: chart-repo
  interval: 10m0s

