apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./muilt-apps
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: chart-repo
  interval: 10m0s
  values:
    app:
      group: authing-next
      name: nginx
    image:
      pullPolicy: IfNotPresent
      registry: docker.io
      tag: 1.23.0
    resources:
      limits:
        cpu: 100m
        memory: 124Mi
      requests:
        cpu: 20m
        memory: 52Mi
    service:
    - name: http
      port: 80

