apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ww-gitops
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://helm.gitops.weave.works

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ww-gitops
  namespace: flux-system
spec:
  chart:
    spec:
      chart: weave-gitops
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: ww-gitops
  interval: 1m0s
  values:
    adminUser:
      create: true
      passwordHash: admin
      username: $2a$10$s.YkIPJ3foKtCmpiwBU6k.zVV0VlFS/ihhF7Jc2vT8WJ8rFkmY7zm
    image:
      repository: ethanliuu/wego-app
    ingress:
      className: nginx
      enabled: true
      hosts:
      - host: flux.deliver1.authing-inc.co
        paths:
        - path: /
          pathType: ImplementationSpecific
      tls:
      - hosts:
        - flux.deliver1.authing-inc.co
        secretName: wild-deliver1-authing-inc-co-cert

